### ISSUE TITLE
Can`t connect node to cluster after upgrade to 1.0

### ISSUE THREAD

**Issue by Pupkur** [opendistro/for-elasticsearch#33]
[2019-08-13T14:46:27,490][WARN ][o.e.c.c.ClusterFormationFailureHelper] [ecsc00a049a2] master not discovered yet: have discovered [{ecsc00a04900}{trnWNt9yRZOv6g5ePnrr1w}{quolIUezQf2v3rTsiOrovg}{10.6.193.183}{10.6.193.183:9300}]; discovery will continue using [10.6.193.183:9300] from hosts providers and [{ecsc00a049a2}{ptzYnK-NRd2j4aGNY4Uw8g}{Wam_N7mlSbu9bezI1bnGXQ}{10.6.218.59}{10.6.218.59:9300}] from last-known cluster state; node term 26, last-accepted version 24391 in term 26
[2019-08-13T14:46:28,705][ERROR][c.a.o.s.a.BackendRegistry] [ecsc00a049a2] Not yet initialized (you may need to run securityadmin)
[2019-08-13T14:46:32,200][INFO ][o.e.c.c.JoinHelper       ] [ecsc00a049a2] failed to join {ecsc00a04900}{trnWNt9yRZOv6g5ePnrr1w}{quolIUezQf2v3rTsiOrovg}{10.6.193.183}{10.6.193.183:9300} with JoinRequest{sourceNode={ecsc00a049a2}{ptzYnK-NRd2j4aGNY4Uw8g}{Wam_N7mlSbu9bezI1bnGXQ}{10.6.218.59}{10.6.218.59:9300}, optionalJoin=Optional.empty}
org.elasticsearch.transport.RemoteTransportException: [ecsc00a04900][10.6.193.183:9300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
	at org.elasticsearch.cluster.coordination.Coordinator$3.onFailure(Coordinator.java:500) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.cluster.coordination.JoinHelper$5.handleException(JoinHelper.java:359) ~[elasticsearch-7.1.1.jar:7.1.1]
	at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityInterceptor$RestoringTransportResponseHandler.handleException(OpenDistroSecurityInterceptor.java:277) ~[?:?]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1124) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.transport.TransportService$8.run(TransportService.java:966) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.1.1.jar:7.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.transport.NodeDisconnectedException: [ecsc00a049a2][10.6.218.59:9300][internal:cluster/coordination/join/validate] disconnected

**Comment by alolita** [comment]
@Pupkur are you still running into these issues? If so can you please file another issue on https://github.com/opendistro-for-elasticsearch/opendistro-build/issues Thanks!
