### ISSUE TITLE
Response error: Unauthorized.

### ISSUE THREAD

**Issue by vanor89** [opendistro/for-elasticsearch#37]
Im getting a response error when trying to connect with basic auth and ssl disabled
```
const client = new Client({ 
  node: 'http://localhost:9200',
  auth: {
    username: 'admin',
    password: 'admin'
  },
  ssl: {
    rejectUnauthorized: false
  }
})
```
```
{ ResponseError: Response Error
    at IncomingMessage.response.on (/home/vanor/code/tstest/node_modules/@elastic/elasticsearch/lib/Transport.js:302:25)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'ResponseError',
  meta:
   { body: 'Unauthorized',
     statusCode: 401,
     headers:
      { 'access-control-allow-credentials': 'true',
        'www-authenticate': 'Basic realm="Open Distro Security"',
        'content-type': 'text/plain; charset=UTF-8',
        'content-length': '12' },
     warnings: null,
     meta:
      { context: null,
        request: [Object],
        name: 'elasticsearch-js',
        connection: [Object],
        attempts: 0,
        aborted: false } } }
```
In my docker compose Im sending this as environment:
`opendistro_security.ssl.http.enabled: 'false'`
Im using the `0.9.0` image, and using the 6.x client node version, Ive noticed that the newer version of the client works, but the repo tells you to match whats in your instance, which is 6.x so I'm wondering whats going on or what I gotta to do get this working on local development

**Comment by vanor89** [comment]
Just realized I was usen an older version of the client, it appears to have been fixed by 6.8.2, closing, sorry.
